### ISSUE TITLE
Minimum orientdb support

### ISSUE THREAD

**Issue by ArkeologeN** [orientechnologies/orientdb-js#2]
Hi,

I'd like to know what's the minimum db version required in-order to use this wrapper? We're currently using `orientdb` in nodejs with `orient 1.3`. However, due to stunning features, we want to switch over `orient 1.6`

If this wrapper is handy enough with it and fully compatible with `gremlin` also without anymore effort, then I think we (at `Kuew`) should contributing it as well.

**Comment by lvca** [comment]
The minimum version should 1.4 but I've not tested with it. I suggest you to upgrade to 1.6.3 for many reasons.
